apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
      - name: Get commit details
        uses: docker://alpine/git:latest
        shell: sh
        run: |
          echo "Commit Information:"
          echo "Commit Hash: $(git rev-parse HEAD)"
          echo "Commit Message: $(git log -1 --pretty=%B)"
          echo "Commit Author: $(git log -1 --pretty=%an)"
          echo "Commit Date: $(git log -1 --pretty=%ad)"
          
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

