apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      commit_details: ${{ steps.commitinfo.outputs.commit_details }}
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1

      - name: Get commit details
        uses: docker://alpine/git:latest
        id: commitinfo
        run: |
          # Get the last 10 commit hashes and messages in the format of "Commit ID - Commit Message"
          COMMIT_DETAILS=$(git log -n 10 --pretty=format:"%H - %s")

          echo "Last 10 Commit Details: $COMMIT_DETAILS"

          # Save the commit details to CloudBees output
          echo "$COMMIT_DETAILS" > $CLOUDBEES_OUTPUTS/commit_details

      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Last 10 Commit Information
            - "${{ steps.commitinfo.outputs.commit_details }}"
