apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      commit_ids: ${{ steps.commitinfo.outputs.commit_ids }}
      commit_msgs: ${{ steps.commitinfo.outputs.commit_msgs }}
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1

      - name: Get commit details
        uses: docker://alpine/git:latest
        id: commitinfo
        run: |
          # Get the last 10 commit hashes and messages
          COMMIT_IDS=$(git log -n 10 --pretty=format:"%H")
          COMMIT_MSGS=$(git log -n 10 --pretty=format:"%s")

          echo "Last 10 Commit IDs: $COMMIT_IDS"
          echo "Last 10 Commit Messages: $COMMIT_MSGS"

          # Save commit details to CloudBees outputs
          echo "$COMMIT_IDS" > $CLOUDBEES_OUTPUTS/commit_ids
          echo "$COMMIT_MSGS" > $CLOUDBEES_OUTPUTS/commit_msgs

      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Commit Information
            - **Last 10 Commit IDs:** "${{ steps.commitinfo.outputs.commit_ids }}"
            - **Last 10 Commit Messages:** "${{ steps.commitinfo.outputs.commit_msgs }}"
